name: Run tests

on:
  push:
    branches: [ master ]

jobs:
  build_android:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.10.0'
      - run: flutter pub get
      - run: flutter test